@startuml
'https://plantuml.com/class-diagram

class TodoList {
    main()
    start()
}

class TodoListController {
    FXML Fields
    ItemList: list
}

class SingleListController {
    FXML Fields
    ItemList itemList
    backButtonClicked()
    addButtonClicked()
    removeButtonClicked()
    saveButtonClicked()
    editButtonClicked()
    addToList()
    removeFromList()
    updateItem()
    initList()
    refresh()
}

class Item {
    String description
    String date
    Boolean completion
    Item()
    getDescription()
    setDescription()
    getDate()
    setDate()
    isComplete()
    setCompletion()
    toString()
}

class ItemList {
    String title
    Item: items
    ItemList()
    getTitle()
    setTitle()
}

javafx.Application <|- TodoList
TodoList -- TodoListController
TodoListController -- SingleListController
TodoListController -- ItemList
SingleListController - ItemList
ItemList - Item

@enduml